package beca;


/**
* beca/BecaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Beca.idl
* miércoles 21 de noviembre de 2018 04:34:28 PM CST
*/

abstract public class BecaHelper
{
  private static String  _id = "IDL:beca/Beca:1.0";

  public static void insert (org.omg.CORBA.Any a, beca.Beca that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static beca.Beca extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (beca.BecaHelper.id (), "Beca");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static beca.Beca read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_BecaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, beca.Beca value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static beca.Beca narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof beca.Beca)
      return (beca.Beca)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      beca._BecaStub stub = new beca._BecaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static beca.Beca unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof beca.Beca)
      return (beca.Beca)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      beca._BecaStub stub = new beca._BecaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
