package beca;


/**
* beca/BecaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Beca.idl
* miércoles 21 de noviembre de 2018 04:34:28 PM CST
*/

public abstract class BecaPOA extends org.omg.PortableServer.Servant
 implements beca.BecaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getListado", new java.lang.Integer (0));
    _methods.put ("getPromedioListado", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // beca/Beca/getListado
       {
         String cs = in.read_string ();
         beca.Llistado $result[] = null;
         $result = this.getListado (cs);
         out = $rh.createReply();
         beca.cotsHelper.write (out, $result);
         break;
       }

       case 1:  // beca/Beca/getPromedioListado
       {
         String cs = in.read_string ();
         double $result = (double)0;
         $result = this.getPromedioListado (cs);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:beca/Beca:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Beca _this() 
  {
    return BecaHelper.narrow(
    super._this_object());
  }

  public Beca _this(org.omg.CORBA.ORB orb) 
  {
    return BecaHelper.narrow(
    super._this_object(orb));
  }


} // class BecaPOA
