package beca;

/**
* beca/BecaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Beca.idl
* miércoles 21 de noviembre de 2018 04:34:28 PM CST
*/

public final class BecaHolder implements org.omg.CORBA.portable.Streamable
{
  public beca.Beca value = null;

  public BecaHolder ()
  {
  }

  public BecaHolder (beca.Beca initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = beca.BecaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    beca.BecaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return beca.BecaHelper.type ();
  }

}
