package beca;


/**
* beca/BecaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Beca.idl
* miércoles 21 de noviembre de 2018 04:34:28 PM CST
*/

public interface BecaOperations 
{
  beca.Llistado[] getListado (String cs);
  double getPromedioListado (String cs);
} // interface BecaOperations
