package beca;


/**
* beca/cotsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Beca.idl
* miércoles 21 de noviembre de 2018 04:34:28 PM CST
*/

public final class cotsHolder implements org.omg.CORBA.portable.Streamable
{
  public beca.Llistado value[] = null;

  public cotsHolder ()
  {
  }

  public cotsHolder (beca.Llistado[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = beca.cotsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    beca.cotsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return beca.cotsHelper.type ();
  }

}
