package beca;


/**
* beca/Llistado.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Beca.idl
* miércoles 21 de noviembre de 2018 04:34:28 PM CST
*/

public final class Llistado implements org.omg.CORBA.portable.IDLEntity
{
  public long numListado = (long)0;
  public String dateListado = null;
  public double valAction = (double)0;
  public String codeSociety = null;

  public Llistado ()
  {
  } // ctor

  public Llistado (long _numListado, String _dateListado, double _valAction, String _codeSociety)
  {
    numListado = _numListado;
    dateListado = _dateListado;
    valAction = _valAction;
    codeSociety = _codeSociety;
  } // ctor

} // class Llistado
