package beca;


/**
* beca/LlistadoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Beca.idl
* miércoles 21 de noviembre de 2018 04:34:28 PM CST
*/

abstract public class LlistadoHelper
{
  private static String  _id = "IDL:beca/Llistado:1.0";

  public static void insert (org.omg.CORBA.Any a, beca.Llistado that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static beca.Llistado extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_longlong);
          _members0[0] = new org.omg.CORBA.StructMember (
            "numListado",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "dateListado",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[2] = new org.omg.CORBA.StructMember (
            "valAction",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "codeSociety",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (beca.LlistadoHelper.id (), "Llistado", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static beca.Llistado read (org.omg.CORBA.portable.InputStream istream)
  {
    beca.Llistado value = new beca.Llistado ();
    value.numListado = istream.read_longlong ();
    value.dateListado = istream.read_string ();
    value.valAction = istream.read_double ();
    value.codeSociety = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, beca.Llistado value)
  {
    ostream.write_longlong (value.numListado);
    ostream.write_string (value.dateListado);
    ostream.write_double (value.valAction);
    ostream.write_string (value.codeSociety);
  }

}
